<a href="https://colab.research.google.com/github/Riccardolotorto/MachineLearning_Python/blob/main/Esercizio_Regressione_Lineare_studenti.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# Import the required libraries:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [6]:
# Read the CSV file:
data = pd.read_csv("/content/drive/MyDrive/Machine Learning Python/Machine Learning/data/student-mat.csv", sep = ";")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [7]:
#elimino delle colonne inutili (quelle di tipo stringa) dal dataset
data = data.drop(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'paid', 'nursery'], axis = 1)

In [ ]:
data

In [9]:
#sostituisco tutti i valori yes o no con 1 e 0 a queste colonne
data['schoolsup'] = data['schoolsup'].replace(['yes', 'no'], [1, 0])
data['famsup'] = data['famsup'].replace(['yes', 'no'], [1, 0])
data['activities'] = data['activities'].replace(['yes', 'no'], [1, 0])
data['higher'] = data['higher'].replace(['yes', 'no'], [1, 0])
data['internet'] = data['internet'].replace(['yes', 'no'], [1, 0])
data['romantic'] = data['romantic'].replace(['yes', 'no'], [1, 0])

In [ ]:
data

In [12]:
X = data[[ 'age', 'Medu', 'Fedu','traveltime',
 'studytime','failures', 'schoolsup', 'famsup', 'activities', 'higher', 'internet', 'romantic', 'famrel', 'freetime',
           'goout', 'Dalc', 'Walc', 'health', 'absences']]
X

age  Medu  Fedu  traveltime  studytime  failures  schoolsup  famsup  \
0     18     4     4           2          2         0          1       0   
1     17     1     1           1          2         0          0       1   
2     15     1     1           1          2         3          1       0   
3     15     4     2           1          3         0          0       1   
4     16     3     3           1          2         0          0       1   
..   ...   ...   ...         ...        ...       ...        ...     ...   
390   20     2     2           1          2         2          0       1   
391   17     3     1           2          1         0          0       0   
392   21     1     1           1          1         3          0       0   
393   18     3     2           3          1         0          0       0   
394   19     1     1           1          1         0          0       0   

     activities  higher  internet  romantic  famrel  freetime  goout  Dalc  \
0             0       1         0         0       4         3      4     1   
1             0       1         1         0       5         3      3     1   
2             0       1         1         0       4         3      2     2   
3             1       1         1         1       3         2      2     1   
4             0       1         0         0       4         3      2     1   
..          ...     ...       ...       ...     ...       ...    ...   ...   
390           0       1         0         0       5         5      4     4   
391           0       1         1         0       2         4      5     3   
392           0       1         0         0       5         5      3     3   
393           0       1         1         0       4         4      1     3   
394           0       1         1         0       3         2      3     3   

     Walc  health  absences  
0       1       3         6  
1       1       3         4  
2       3       3        10  
3       1       5         2  
4       2       5         4  
..    ...     ...       ...  
390     5       4        11  
391     4       2         3  
392     3       3         3  
393     4       5         0  
394     3       5         5  

[395 rows x 19 columns]

In [13]:
Y = data['G3']
Y

0       6
1       6
2      10
3      15
4      10
       ..
390     9
391    16
392     7
393    10
394     9
Name: G3, Length: 395, dtype: int64

In [ ]:
#trasformiamo da dataframe in matrice numpy per poter allenare il metodo

In [14]:
Xnp = X.to_numpy()
Xnp

array([[18,  4,  4, ...,  1,  3,  6],
       [17,  1,  1, ...,  1,  3,  4],
       [15,  1,  1, ...,  3,  3, 10],
       ...,
       [21,  1,  1, ...,  3,  3,  3],
       [18,  3,  2, ...,  4,  5,  0],
       [19,  1,  1, ...,  3,  5,  5]])

In [15]:
Ynp = Y.to_numpy()
Ynp

array([ 6,  6, 10, 15, 10, 15, 11,  6, 19, 15,  9, 12, 14, 11, 16, 14, 14,
       10,  5, 10, 15, 15, 16, 12,  8,  8, 11, 15, 11, 11, 12, 17, 16, 12,
       15,  6, 18, 15, 11, 13, 11, 12, 18, 11,  9,  6, 11, 20, 14,  7, 13,
       13, 10, 11, 13, 10, 15, 15,  9, 16, 11, 11,  9,  9, 10, 15, 12,  6,
        8, 16, 15, 10,  5, 14, 11, 10, 10, 11, 10,  5, 12, 11,  6, 15, 10,
        8,  6, 14, 10,  7,  8, 18,  6, 10, 14, 10, 15, 10, 14,  8,  5, 17,
       14,  6, 18, 11,  8, 18, 13, 16, 19, 10, 13, 19,  9, 16, 14, 13,  8,
       13, 15, 15, 13, 13,  8, 12, 11,  9,  0, 18,  0,  0, 12, 11,  0,  0,
        0,  0, 12, 15,  0,  9, 11, 13,  0, 11,  0, 11,  0, 10,  0, 14, 10,
        0, 12,  8, 13, 10, 15, 12,  0,  7,  0, 10,  7, 12, 10, 16,  0, 14,
        0, 16, 10,  0,  9,  9, 11,  6,  9, 11,  8, 12, 17,  8, 12, 11, 11,
       15,  9, 10, 13,  9,  8, 10, 14, 15, 16, 10, 18, 10, 16, 10, 10,  6,
       11,  9,  7, 13, 10,  7,  8, 13, 14,  8, 10, 15,  4,  8,  8, 10,  6,
        0, 17, 13, 14,  7

In [16]:
from sklearn.model_selection import train_test_split # suddivide le osservazioni nei due insiemi

X_train, X_test, y_train, y_test = train_test_split(Xnp, Ynp,
                                                    test_size = 0.33,
                                                    random_state = 123) # fix random seed for replicability

In [17]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((264, 19), (264,), (131, 19), (131,))

In [18]:
print(X_train[:10])
print(f'y_train = {y_train[:10]}')

[[15  2  2  1  4  0  0  1  1  1  1  0  4  3  4  1  1  4  6]
 [17  3  3  1  2  0  0  0  1  1  1  0  4  3  4  1  4  4  4]
 [18  2  1  2  1  0  0  0  1  1  1  1  4  4  3  1  3  5  5]
 [15  2  3  2  1  0  0  1  1  1  0  0  3  5  1  1  1  5  0]
 [18  2  2  1  1  2  0  1  1  1  1  0  3  3  3  1  2  4  0]
 [16  3  3  1  2  0  1  1  1  1  1  0  4  3  3  2  4  5 54]
 [15  4  4  1  1  0  1  1  0  1  1  0  3  3  4  2  3  5  0]
 [16  4  2  1  2  0  0  0  1  1  1  0  4  5  1  1  3  5  2]
 [17  2  2  1  2  0  0  1  0  1  0  1  4  2  2  1  1  3 12]
 [18  1  1  2  4  0  0  1  1  1  0  0  5  2  2  1  1  3  1]]
y_train = [14  6  7  6  0 11 11 16  9 12]


**Creazione regressione lineare**

In [19]:
#Using sklearn package to model data :
regr = linear_model.LinearRegression()
regr.fit(X_train,y_train)
predict = regr.predict(X_test)

In [20]:
print(f'dati predetti dal metodo = {predict[:10].round(decimals=2)}') # dati predetti dal metodo
print(f'dati reali presenti nel dataset di test = {y_test[:10]}') # dati effettivi presenti nel test set

dati predetti dal metodo = [ 6.47 11.99  7.91  9.17  7.13 13.15  9.18  3.61 12.6  11.46]
dati reali presenti nel dataset di test = [ 8 13 12  0 10 12  5  0 16 13]


**Valutiamo il metodo**

In [21]:
from sklearn.metrics import r2_score, mean_squared_error

# The coefficients
print('Coefficients: \n', regr.coef_)

# The mean squared error
print('Mean squared error: %.2f' %mean_squared_error(y_test, predict))

# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f' %r2_score(y_test, predict))

Coefficients: 
 [-0.3823122   0.37956339  0.31887174 -0.32346748  0.14332017 -1.31418016
 -1.78612957 -1.21307019 -0.18803552  2.07051364  0.33866288 -0.35511897
 -0.03051249  0.45832341 -0.38138491 -0.13585605  0.23518437 -0.20937253
  0.04765581]
Mean squared error: 16.92
Coefficient of determination: 0.21


#Riproviamo il metodo (G1 e G2)

In [ ]:
X1 = data[['G1', 'G2']]
X1

In [ ]:
Y1 = data[['G3']]
Y1

In [ ]:
X1np = X1.to_numpy()
X1np

In [ ]:
Y1np = Y1.to_numpy()
Y1np

In [27]:
from sklearn.model_selection import train_test_split # suddivide le osservazioni nei due insiemi

X1_train, X1_test, y1_train, y1_test = train_test_split(X1np, Y1np,
                                                    test_size = 0.33,
                                                    random_state = 123) # fix random seed for replicability

In [28]:
X1_train.shape,y1_train.shape,X1_test.shape,y1_test.shape

((264, 2), (264, 1), (131, 2), (131, 1))

In [29]:
print(X1_train[:10])
print(f'y_train = {y1_train[:10]}')

[[11 13]
 [ 6  5]
 [ 7  6]
 [ 8  7]
 [ 7  4]
 [11 12]
 [ 8 10]
 [15 15]
 [11  9]
 [12 12]]
y_train = [[14]
 [ 6]
 [ 7]
 [ 6]
 [ 0]
 [11]
 [11]
 [16]
 [ 9]
 [12]]


In [30]:
#Using sklearn package to model data :
regr1 = linear_model.LinearRegression()
regr1.fit(X1_train,y1_train)
predict1 = regr1.predict(X1_test)

In [31]:
print(f'dati predetti dal metodo = {predict1[:10].round(decimals=2)}') # dati predetti dal metodo
print(f'dati reali presenti nel dataset di test = {y1_test[:10]}') # dati effettivi presenti nel test set

dati predetti dal metodo = [[ 7.97]
 [13.05]
 [11.78]
 [ 5.19]
 [ 9.83]
 [ 9.24]
 [ 3.63]
 [ 4.07]
 [15.29]
 [11.78]]
dati reali presenti nel dataset di test = [[ 8]
 [13]
 [12]
 [ 0]
 [10]
 [12]
 [ 5]
 [ 0]
 [16]
 [13]]


In [33]:
from sklearn.metrics import r2_score, mean_squared_error

# The coefficients
print('Coefficients: \n', regr1.coef_)

# The mean squared error
print('Mean squared error: %.2f' %mean_squared_error(y1_test, predict1))

# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f' %r2_score(y1_test, predict1))

Coefficients: 
 [[0.14639778 0.97560801]]
Mean squared error: 3.73
Coefficient of determination: 0.83


#Riproviamo il metodo (activities)

In [ ]:
X2 = data[['activities']]
X2

In [ ]:
Y2 = data[['G3']]
Y2

In [ ]:
X2np = X2.to_numpy()
X2np

In [ ]:
Y2np = Y2.to_numpy()
Y2np

In [40]:
from sklearn.model_selection import train_test_split # suddivide le osservazioni nei due insiemi

X2_train, X2_test, y2_train, y2_test = train_test_split(X2np, Y2np,
                                                    test_size = 0.33,
                                                    random_state = 123) # fix random seed for replicability

In [42]:
#Using sklearn package to model data :
regr2 = linear_model.LinearRegression()
regr2.fit(X2_train,y2_train)
predict2 = regr2.predict(X2_test)

In [ ]:
print(f'dati predetti dal metodo = {predict2[:10].round(decimals=2)}') # dati predetti dal metodo
print(f'dati reali presenti nel dataset di test = {y2_test[:10]}') # dati effettivi presenti nel test set

In [44]:
from sklearn.metrics import r2_score, mean_squared_error

# The coefficients
print('Coefficients: \n', regr2.coef_)

# The mean squared error
print('Mean squared error: %.2f' %mean_squared_error(y2_test, predict2))

# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f' %r2_score(y2_test, predict2))

Coefficients: 
 [[0.60972222]]
Mean squared error: 21.96
Coefficient of determination: -0.02
