<a href="https://colab.research.google.com/github/Riccardolotorto/MachineLearning_Python/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import the required libraries:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
# Read the CSV file:
data = pd.read_csv("/content/drive/MyDrive/Machine Learning Python/Machine Learning/data/Fuel.csv")
data.head()

MODELYEAR   MAKE       MODEL VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0       2014  ACURA         ILX      COMPACT         2.0          4   
1       2014  ACURA         ILX      COMPACT         2.4          4   
2       2014  ACURA  ILX HYBRID      COMPACT         1.5          4   
3       2014  ACURA     MDX 4WD  SUV - SMALL         3.5          6   
4       2014  ACURA     RDX AWD  SUV - SMALL         3.5          6   

  TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0          AS5        Z                   9.9                  6.7   
1           M6        Z                  11.2                  7.7   
2          AV7        Z                   6.0                  5.8   
3          AS6        Z                  12.7                  9.1   
4          AS6        Z                  12.1                  8.7   

   FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                   8.5                        33           196  
1                   9.6                        29           221  
2                   5.9                        48           136  
3                  11.1                        25           255  
4                  10.6                        27           244

In [5]:
# Consider features we want to work on:
X = data[[ 'ENGINESIZE', 'CYLINDERS', 'FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY',
 'FUELCONSUMPTION_COMB','FUELCONSUMPTION_COMB_MPG']]
X

ENGINESIZE  CYLINDERS  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0            2.0          4                   9.9                  6.7   
1            2.4          4                  11.2                  7.7   
2            1.5          4                   6.0                  5.8   
3            3.5          6                  12.7                  9.1   
4            3.5          6                  12.1                  8.7   
...          ...        ...                   ...                  ...   
1062         3.0          6                  13.4                  9.8   
1063         3.2          6                  13.2                  9.5   
1064         3.0          6                  13.4                  9.8   
1065         3.2          6                  12.9                  9.3   
1066         3.2          6                  14.9                 10.2   

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  
0                      8.5                        33  
1                      9.6                        29  
2                      5.9                        48  
3                     11.1                        25  
4                     10.6                        27  
...                    ...                       ...  
1062                  11.8                        24  
1063                  11.5                        25  
1064                  11.8                        24  
1065                  11.3                        25  
1066                  12.8                        22  

[1067 rows x 6 columns]

In [6]:
Y = data['CO2EMISSIONS']
Y

0       196
1       221
2       136
3       255
4       244
       ... 
1062    271
1063    264
1064    271
1065    260
1066    294
Name: CO2EMISSIONS, Length: 1067, dtype: int64

In [7]:
Xnp = X.to_numpy()
Xnp

array([[ 2. ,  4. ,  9.9,  6.7,  8.5, 33. ],
       [ 2.4,  4. , 11.2,  7.7,  9.6, 29. ],
       [ 1.5,  4. ,  6. ,  5.8,  5.9, 48. ],
       ...,
       [ 3. ,  6. , 13.4,  9.8, 11.8, 24. ],
       [ 3.2,  6. , 12.9,  9.3, 11.3, 25. ],
       [ 3.2,  6. , 14.9, 10.2, 12.8, 22. ]])

In [8]:
Ynp = Y.to_numpy()
Ynp

array([196, 221, 136, ..., 271, 260, 294])

In [9]:
from sklearn.model_selection import train_test_split # suddivide le osservazioni nei due insiemi

X_train, X_test, y_train, y_test = train_test_split(Xnp, Ynp,
                                                    test_size = 0.33,
                                                    random_state = 123) # fix random seed for replicability

In [10]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((714, 6), (714,), (353, 6), (353,))

In [11]:
print(X_train[:10])
print(f'y_train = {y_train[:10]}')

[[ 2.5  5.  10.9  8.4  9.8 29. ]
 [ 2.   4.   9.1  6.2  7.8 36. ]
 [ 2.4  4.  10.5  7.3  9.1 31. ]
 [ 2.4  4.   9.6  6.5  8.2 34. ]
 [ 3.5  6.  13.3  9.3 11.5 25. ]
 [ 4.6  8.  16.9 12.8 15.1 19. ]
 [ 1.6  4.   9.1  6.7  8.  35. ]
 [ 3.5  6.  13.7  9.9 12.  24. ]
 [ 5.6  8.  17.9 12.8 15.6 18. ]
 [ 3.6  6.  16.8 10.3 13.9 20. ]]
y_train = [225 179 209 189 265 347 184 276 359 222]


In [12]:
#Using sklearn package to model data :
regr = linear_model.LinearRegression()

In [13]:
regr.fit(X_train,y_train)

LinearRegression()

In [14]:
predict = regr.predict(X_test)

In [15]:
print(f'dati predetti dal metodo = {predict[:10].round(decimals=2)}') # dati predetti dal metodo
print(f'dati reali presenti nel dataset di test = {y_test[:10]}') # dati effettivi presenti nel test set

dati predetti dal metodo = [162.67 286.59 268.58 304.93 290.59 372.24 348.49 213.04 320.98 202.76]
dati reali presenti nel dataset di test = [161 308 285 297 230 359 277 225 317 209]


In [16]:
from sklearn.metrics import r2_score, mean_squared_error

# The coefficients
print('Coefficients: \n', regr.coef_)

# The mean squared error
print('Mean squared error: %.2f' %mean_squared_error(y_test, predict))

# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f' %r2_score(y_test, predict))

Coefficients: 
 [ 7.79776025  8.34900746  2.4522724   7.69091091 -6.09077422 -3.85525307]
Mean squared error: 481.34
Coefficient of determination: 0.87


In [17]:
unknownCar = [[ 1.5,  4. ,  6. ,  5.8,  5.9, 48. ]] # third record - true value 136
predictUnknownCar = regr.predict(unknownCar)
predictUnknownCar

array([132.83861336])